package ui;

import model.Personaje;
import utils.PersonajeFactory;

import javax.swing.*;
import java.awt.*;
import java.util.List;

// Pantalla donde el jugador elige su personaje secreto antes del modo Jugador vs. Máquinas.
public class PanelEleccionPersonaje {
    private JPanel raiz;
    private JLabel lblTitulo;
    private JLabel lblSubtitulo;
    private JPanel contenedorTablero;
    private JButton btnVolver;

    private final VentanaPrincipal ventana;
    private final List<Personaje> personajes;
    private final PanelTablero tablero = new PanelTablero();

    public PanelEleccionPersonaje(VentanaPrincipal ventana) {
        this.ventana = ventana;
        this.personajes = PersonajeFactory.crearPersonajes();

        contenedorTablero.setLayout(new BorderLayout());
        contenedorTablero.add(tablero, BorderLayout.CENTER);
        tablero.mostrar(personajes, e -> confirmarEleccion((TarjetaPersonaje) e.getSource()));

        btnVolver.addActionListener(e -> ventana.mostrarPantalla("MODOS"));
    }

    private void confirmarEleccion(TarjetaPersonaje tarjeta) {
        Personaje elegido = tarjeta.getPersonaje();
        tarjeta.setSeleccionada(true);

        int respuesta = JOptionPane.showConfirmDialog(
                raiz,
                "¿Querés elegir a " + elegido.getNombre() + " como tu personaje secreto?\n"
                        + "No vas a poder cambiarlo durante la partida.",
                "Confirmar personaje",
                JOptionPane.YES_NO_OPTION
        );

        if (respuesta == JOptionPane.YES_OPTION) {
            ventana.iniciarJugadorVsMaquinas(elegido, personajes);
        } else {
            tarjeta.setSeleccionada(false);
        }
    }

    public JPanel getRaiz() {
        return raiz;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        raiz = new JPanel();
        raiz.setLayout(new GridBagLayout());
        raiz.setBackground(new Color(-1));
        lblTitulo = new JLabel();
        lblTitulo.setForeground(new Color(-16777216));
        lblTitulo.setText("Elegí tu personaje secreto");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        raiz.add(lblTitulo, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        raiz.add(spacer1, gbc);
        lblSubtitulo = new JLabel();
        lblSubtitulo.setForeground(new Color(-16777216));
        lblSubtitulo.setText("Las máquinas van a tener que adivinarlo");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        raiz.add(lblSubtitulo, gbc);
        contenedorTablero = new JPanel();
        contenedorTablero.setLayout(new GridBagLayout());
        contenedorTablero.setBackground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        raiz.add(contenedorTablero, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        raiz.add(spacer2, gbc);
        btnVolver = new JButton();
        btnVolver.setText("Volver");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        raiz.add(btnVolver, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        raiz.add(spacer3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        raiz.add(spacer4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        raiz.add(spacer5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        raiz.add(spacer6, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return raiz;
    }

}
