package ui;

import javax.swing.*;
import java.awt.*;

public class PanelModosDeJuego {
    private JPanel raiz;
    private JLabel lblTitulo;
    private JPanel buttons;
    private JButton btnModo1;
    private JButton btnModo2;
    private JButton btnSalir;

    public PanelModosDeJuego(VentanaPrincipal ventana) {
        btnModo1.addActionListener(e -> ventana.mostrarEleccionPersonaje());
        btnModo2.addActionListener(e -> ventana.iniciarMaquinaVsMaquina());
        btnSalir.addActionListener(e -> ventana.mostrarPantalla("MENU"));
    }

    public JPanel getRaiz() {
        return raiz;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        raiz = new JPanel();
        raiz.setLayout(new GridBagLayout());
        raiz.setBackground(new Color(-1));
        lblTitulo = new JLabel();
        lblTitulo.setForeground(new Color(-16777216));
        lblTitulo.setHorizontalAlignment(0);
        lblTitulo.setText("Modos de juego");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        raiz.add(lblTitulo, gbc);
        buttons = new JPanel();
        buttons.setLayout(new GridBagLayout());
        buttons.setBackground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        raiz.add(buttons, gbc);
        btnModo1 = new JButton();
        btnModo1.setText("Jugador vs. Máquina");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttons.add(btnModo1, gbc);
        btnModo2 = new JButton();
        btnModo2.setText("Máquina vs. Máquina");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttons.add(btnModo2, gbc);
        btnSalir = new JButton();
        btnSalir.setText("Volver atrás");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        buttons.add(btnSalir, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttons.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttons.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        buttons.add(spacer3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return raiz;
    }

}
