package ui;

import javax.swing.*;
import java.awt.*;
import java.util.List;

// Panel lateral que muestra en texto continuo los mensajes de la partida
// (turnos, preguntas, respuestas, razonamiento de las máquinas y resultado).
public class PanelLogs {
    private JPanel raiz;
    private JLabel lblTitulo;
    private JScrollPane scrollLogs;
    private JTextArea txtLogs;

    public void agregarMensajes(List<String> mensajes) {
        for (String mensaje : mensajes) {
            txtLogs.append(mensaje + "\n");
        }
        txtLogs.setCaretPosition(txtLogs.getDocument().getLength());
    }

    public JPanel getRaiz() {
        return raiz;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        raiz = new JPanel();
        raiz.setLayout(new GridBagLayout());
        raiz.setBackground(new Color(-3355444));
        lblTitulo = new JLabel();
        lblTitulo.setForeground(new Color(-16777216));
        lblTitulo.setHorizontalAlignment(0);
        lblTitulo.setText("Logs");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        raiz.add(lblTitulo, gbc);
        scrollLogs = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 5, 5, 5);
        raiz.add(scrollLogs, gbc);
        txtLogs = new JTextArea();
        txtLogs.setEditable(false);
        txtLogs.setLineWrap(true);
        txtLogs.setWrapStyleWord(true);
        scrollLogs.setViewportView(txtLogs);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return raiz;
    }
}
