package ui;

import score.Puntaje;
import score.RepositorioPuntajes;
import score.ScoreRepository;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

// Pantalla del marcador de records: puesto, jugador, partidas jugadas, rondas y partidas ganadas,
// ordenado por partidas y, a igualdad, por rondas. Si no hay puntajes muestra un mensaje.
public class PanelPuntajes {
    private static final String[] COLUMNAS = {"Puesto", "Jugador", "Partidas jugadas", "Rondas ganadas", "Partidas ganadas"};

    private JPanel raiz;
    private JLabel lblTitulo;
    private JScrollPane scrollTabla;
    private JTable tablaPuntajes;
    private JLabel lblSinPuntajes;
    private JButton btnSalir;

    private final DefaultTableModel modeloTabla = new DefaultTableModel(COLUMNAS, 0) {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };

    public PanelPuntajes(VentanaPrincipal ventana) {
        tablaPuntajes.setModel(modeloTabla);
        tablaPuntajes.getTableHeader().setReorderingAllowed(false);
        tablaPuntajes.setRowSelectionAllowed(false);
        tablaPuntajes.setFocusable(false);

        btnSalir.addActionListener(e -> ventana.mostrarPantalla("MENU"));
    }

    // Se llama antes de mostrar la pantalla, así la tabla refleja las partidas recién jugadas.
    public void cargar() {
        // Instancia nueva para releer el archivo: la partida registra las victorias con su propio repositorio.
        RepositorioPuntajes repositorio = new ScoreRepository();
        List<Puntaje> puntajes = repositorio.obtenerPuntajesOrdenados();

        modeloTabla.setRowCount(0);
        int puesto = 1;
        for (Puntaje puntaje : puntajes) {
            modeloTabla.addRow(new Object[]{puesto, puntaje.getNombreJugador(), puntaje.getPartidasJugadas(),
                    puntaje.getRondasGanadas(), puntaje.getPartidasGanadas()});
            puesto++;
        }

        boolean hayPuntajes = !puntajes.isEmpty();
        scrollTabla.setVisible(hayPuntajes);
        lblSinPuntajes.setVisible(!hayPuntajes);
    }

    public JPanel getRaiz() {
        return raiz;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        raiz = new JPanel();
        raiz.setLayout(new GridBagLayout());
        raiz.setBackground(new Color(-1));
        lblTitulo = new JLabel();
        lblTitulo.setForeground(new Color(-16777216));
        lblTitulo.setHorizontalAlignment(0);
        lblTitulo.setText("Puntajes");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(20, 20, 10, 20);
        raiz.add(lblTitulo, gbc);
        scrollTabla = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 20, 10, 20);
        raiz.add(scrollTabla, gbc);
        tablaPuntajes = new JTable();
        scrollTabla.setViewportView(tablaPuntajes);
        lblSinPuntajes = new JLabel();
        lblSinPuntajes.setForeground(new Color(-16777216));
        lblSinPuntajes.setHorizontalAlignment(0);
        lblSinPuntajes.setText("Todavía no hay puntajes registrados.");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 20, 10, 20);
        raiz.add(lblSinPuntajes, gbc);
        btnSalir = new JButton();
        btnSalir.setText("Volver");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.insets = new Insets(0, 20, 20, 20);
        raiz.add(btnSalir, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return raiz;
    }
}
