package ui;

import model.Filtro;
import model.FiltroAplicado;
import model.TipoFiltro;
import utils.FiltroFactory;

import javax.swing.*;
import java.awt.*;
import java.util.function.Consumer;

// Panel de botones de filtros del tablero de juego: un botón por TipoFiltro.

public class PanelFiltros {
    private static final int COLUMNAS = 4;
    private static final int SEPARACION = 5;
    private static final String CARTA_FILTROS = "FILTROS";
    private static final String CARTA_VALORES = "VALORES";

    private JPanel raiz;
    private JLabel lblTitulo;
    private JPanel contenedorBotones;

    private final CardLayout cartas = new CardLayout();
    private final JPanel panelFiltros = new JPanel();
    private final JPanel panelValores = new JPanel(new BorderLayout());
    private final JPanel contenedorValores = new JPanel();

    private Consumer<FiltroAplicado> alPreguntar;

    public PanelFiltros() {
        contenedorBotones.setLayout(cartas);

        panelFiltros.setLayout(new GridLayout(2, COLUMNAS, SEPARACION, SEPARACION));
        for (Filtro filtro : FiltroFactory.crearFiltros()) {
            panelFiltros.add(crearBotonFiltro(filtro));
        }

        JButton btnVolver = new JButton("< Volver");
        btnVolver.addActionListener(e -> mostrarFiltros());
        panelValores.add(contenedorValores, BorderLayout.CENTER);
        panelValores.add(btnVolver, BorderLayout.SOUTH);

        contenedorBotones.add(panelFiltros, CARTA_FILTROS);
        contenedorBotones.add(panelValores, CARTA_VALORES);
    }

    private JButton crearBotonFiltro(Filtro filtro) {
        JButton boton = new JButton(filtro.getNombre());
        boton.addActionListener(e -> mostrarValores(filtro));
        return boton;
    }

    private void mostrarValores(Filtro filtro) {
        contenedorValores.removeAll();
        int columnas = Math.min(filtro.getValores().length, COLUMNAS);
        contenedorValores.setLayout(new GridLayout(0, columnas, SEPARACION, SEPARACION));

        for (String valor : filtro.getValores()) {
            JButton boton = new JButton(etiquetaDe(valor));
            boton.addActionListener(e -> seleccionarValor(filtro.getTipo(), valor));
            contenedorValores.add(boton);
        }

        contenedorValores.revalidate();
        contenedorValores.repaint();
        cartas.show(contenedorBotones, CARTA_VALORES);
    }

    private void mostrarFiltros() {
        cartas.show(contenedorBotones, CARTA_FILTROS);
    }

    private void seleccionarValor(TipoFiltro tipo, String valor) {
        FiltroAplicado filtroAplicado = new FiltroAplicado(tipo, valor);
        mostrarFiltros();
        if (alPreguntar != null) {
            alPreguntar.accept(filtroAplicado);
        }
    }


    private String etiquetaDe(String valor) {
        if ("true".equalsIgnoreCase(valor)) {
            return "Sí";
        }
        if ("false".equalsIgnoreCase(valor)) {
            return "No";
        }
        String minusculas = valor.toLowerCase();
        return Character.toUpperCase(minusculas.charAt(0)) + minusculas.substring(1);
    }

    // Quien monte este panel se suscribe acá para recibir cada pregunta armada.
    public void setAlPreguntar(Consumer<FiltroAplicado> alPreguntar) {
        this.alPreguntar = alPreguntar;
    }

    // Habilita o deshabilita los 8 botones de filtro (p. ej. cuando no es el turno
    // del jugador o el desafío terminó). Como la vista de valores solo se llega a
    // través de ellos, alcanza con deshabilitar esta carta.
    public void setHabilitado(boolean habilitado) {
        for (Component boton : panelFiltros.getComponents()) {
            boton.setEnabled(habilitado);
        }
    }

    public JPanel getRaiz() {
        return raiz;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        raiz = new JPanel();
        raiz.setLayout(new GridBagLayout());
        raiz.setBackground(new Color(-1));
        lblTitulo = new JLabel();
        lblTitulo.setForeground(new Color(-16777216));
        lblTitulo.setText("¿Qué querés preguntar?");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        raiz.add(lblTitulo, gbc);
        contenedorBotones = new JPanel();
        contenedorBotones.setLayout(new GridBagLayout());
        contenedorBotones.setBackground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        raiz.add(contenedorBotones, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return raiz;
    }

}
