package ui;

import javax.swing.*;
import java.awt.*;

public class PanelJuego {
    private JPanel raiz;
    private JLabel lblTitulo;
    private JLabel lblModo;

    public PanelJuego(VentanaPrincipal ventana, int modo) {
        switch (modo) {
            case 1:
                lblModo.setText("Modo de juego: 1");
                return;
            case 2:
                lblModo.setText("Modo de juego: 2");
            default:
                lblModo.setText("No se encontró el modo de juego.");
        }
    }

    public void detener() {

    }

    public JPanel getRaiz() {
        return raiz;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        raiz = new JPanel();
        raiz.setLayout(new GridBagLayout());
        raiz.setBackground(new Color(-1));
        lblTitulo = new JLabel();
        lblTitulo.setForeground(new Color(-16777216));
        lblTitulo.setHorizontalAlignment(0);
        lblTitulo.setText("Juego");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        raiz.add(lblTitulo, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        raiz.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        raiz.add(spacer2, gbc);
        lblModo = new JLabel();
        lblModo.setBackground(new Color(-16777216));
        lblModo.setText("Modo de juego: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        raiz.add(lblModo, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return raiz;
    }

}
