package ui;

import javax.swing.*;
import java.awt.*;

public class PanelBienvenida {
    private JPanel raiz;
    private JLabel lblTitulo;
    private JPanel form;
    private JTextField txtNombre;
    private JButton btnConfirmar;

    public PanelBienvenida(VentanaPrincipal ventana) {
        btnConfirmar.addActionListener(e -> continuar(ventana));
    }

    public void continuar(VentanaPrincipal ventana) {
        String nombre = txtNombre.getText().trim();

        if (!nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ]{3,11}")) {
            JOptionPane.showMessageDialog(raiz,
                    "El nombre debe tener entre 3 y 11 letras, sin números ni espacios.",
                    "Nombre inválido", JOptionPane.WARNING_MESSAGE);
            txtNombre.requestFocus();
            return;
        }

        ventana.setNombreJugador(nombre);
        ventana.mostrarPantalla("MENU");
    }

    public JPanel getRaiz() {
        return raiz;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        raiz = new JPanel();
        raiz.setLayout(new GridBagLayout());
        raiz.setBackground(new Color(-1));
        raiz.setForeground(new Color(-1));
        lblTitulo = new JLabel();
        lblTitulo.setForeground(new Color(-16777216));
        lblTitulo.setHorizontalAlignment(0);
        lblTitulo.setText("Bienvenido a AdivinaAdivinador");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        raiz.add(lblTitulo, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        raiz.add(spacer1, gbc);
        form = new JPanel();
        form.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        form.setBackground(new Color(-1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.BOTH;
        raiz.add(form, gbc);
        txtNombre = new JTextField();
        txtNombre.setColumns(15);
        txtNombre.setHorizontalAlignment(2);
        txtNombre.setText("");
        form.add(txtNombre);
        btnConfirmar = new JButton();
        btnConfirmar.setText("Confirmar");
        form.add(btnConfirmar);
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-16777216));
        label1.setHorizontalAlignment(0);
        label1.setText("¿Cuál es tu nombre?");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        raiz.add(label1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return raiz;
    }

}
